### PR TITLE
travis: update go versions

### PR DESCRIPTION
**Pull request by dvrkps**
.x match latest patch

### CODE REVIEW

**Comment by gdamore** [comment]
This looks good.  Thanks!

**Comment by dolmen** [comment]
Go `1.10` and `tip` should be added too.
Also, it is recommended to have versions specified as strings (`"1.10"` instead of `1.10`) to avoid the versions being deserialized as floats.

**Comment by sbinet** [comment]
if you put, say, `1.10.x`, YAML won't parse that as a float **and** you get the latest patch release, if any.

**Comment by sbinet** [comment]
and `tip` is deprecated in favor of `master`.

**Pull request merged**
