### PR TITLE
Add TravisCI OSX and -race test; update CI Go versions

### PR DESCRIPTION
**Pull request by binary132**
Addresses https://github.com/go-mangos/mangos/issues/238

### CODE REVIEW

**Comment by binary132** [comment]
Looks like the OSX tests may be hanging.

**Comment by gdamore** [comment]
I'm pretty sure this is due to the initialization bug we discussed on gitter -- basically I am making assumptions about the safety of an operation that are not working.  Fixing this will take a bit of effort, and TBH I'm not really sure what the best approach is yet (changing the queue lengths for channels is the problem.)

**Comment by gdamore** [comment]
I think I have a fix for this.

**Comment by binary132** [comment]
Nvm, I see this is in the upstream now.

**Pull request closed without merging**
